name: 'Clubhouse release notes github action'
description: "Scienta's take on release notes using Clubhouse"
author: 'Scienta'
#inputs:
#  github-token:
#    description: 'Github Actions Token or Personal Access Token (PAT)'
#    required: true
#  repository-owner:
#    description: 'Owner of the repository'
#    required: true
#  repository-name:
#    description: 'Name of the repository'
#    required: true
#  head-branch:
#    description: 'Name of the head branch'
#    required: true
#  base-branch-filters:
#    description: 'JSON-string of array of globs to match base branches (uses picomatch)'
#    required: true
#    default: '[]'
#  pr-title:
#    description: 'Title of the Pull Request (Variables: {head}, {base})'
#    default: 'Merge {head} into {base}'
#  pr-body:
#    description: 'Body of the Pull Request (Variables: see title)'
#    default: ''
#  pr-labels:
#    description: 'Labels to add to the PR'
#    default: '[]'
runs:
  using: 'node12'
  main: 'dist/index.js'
